import { db } from '../firebase'
import { collection, doc, getDocs, setDoc } from 'firebase/firestore'

// App-only expense metadata (pin / isFixed and note) lives in Firestore so it
// survives the Google Sheet ↔ Drive-Excel reconciliation, which cannot carry
// these fields reliably (Excel drops isFixed entirely and mangles notes).
// Path: sheets/{sheetId}/expenseMeta/{pinKey}

const metaCol = (sheetId) => collection(db, 'sheets', sheetId, 'expenseMeta')

// A stable identity for an expense, independent of its row id (the id can be
// regenerated by the Excel reconciliation, so it is NOT reliable). Sanitised
// so it is always a valid Firestore document id.
export function expensePinKey({ year, month, categoryId, itemName }) {
  const raw = `${year}_${month}_${categoryId}_${String(itemName || '').trim().toLowerCase()}`
  return raw.replace(/[/\\.#$[\]]/g, '_').slice(0, 400)
}

function withTimeout(promise, ms) {
  return Promise.race([
    promise,
    new Promise((_, reject) => setTimeout(() => reject(new Error('Firebase timeout')), ms))
  ])
}

// Returns a map { [pinKey]: { isFixed?: boolean, note?: string } } of the
// app-only metadata that has been explicitly set.
// Never throws — a Firestore hiccup must not block the dashboard from loading.
export async function fetchExpenseMetaFS(sheetId) {
  if (!sheetId) return {}
  try {
    const snap = await withTimeout(getDocs(metaCol(sheetId)), 10000)
    const map = {}
    snap.docs.forEach(d => { map[d.id] = d.data() })
    return map
  } catch (e) {
    console.warn('[BudgetIQ] Expense meta fetch failed:', e.message)
    return {}
  }
}

// Persist app-only metadata for one expense. Pass only the fields to set —
// e.g. { isFixed } when toggling the pin, { note } when editing the comment,
// or both when saving the expense form. Merges, so other fields are untouched.
export async function setExpenseMetaFS(sheetId, exp, fields = {}) {
  if (!sheetId) return
  const data = {}
  if ('isFixed' in fields) data.isFixed = fields.isFixed === true || fields.isFixed === 'TRUE'
  if ('note' in fields) data.note = fields.note || ''
  if (Object.keys(data).length === 0) return
  const key = expensePinKey(exp)
  await setDoc(doc(db, 'sheets', sheetId, 'expenseMeta', key), data, { merge: true })
}
